/**
 * KIE.AI API Router - Intelligent routing system
 * Routes requests to the correct KIE.AI endpoint based on model ID
 * Handles different API formats and parameter mapping
 */

// Load the endpoints mapping (will be generated by doc analysis)
let endpointsMapping = null;

function loadEndpointsMapping() {
  if (endpointsMapping) return endpointsMapping;
  try {
    endpointsMapping = require('../api-endpoints-mapping.json');
    console.log(`✅ Loaded ${endpointsMapping.endpoints.length} endpoint configurations`);
    return endpointsMapping;
  } catch (error) {
    console.error('❌ Failed to load endpoints mapping:', error.message);
    return { endpoints: [] };
  }
}

/**
 * Find endpoint configuration for a given model ID
 */
function findEndpointForModel(modelId) {
  const mapping = loadEndpointsMapping();

  // Search through all endpoints to find one that supports this modelId
  const endpoint = mapping.endpoints.find(ep =>
    ep.modelIds && ep.modelIds.includes(modelId)
  );

  if (!endpoint) {
    console.warn(`⚠️ No endpoint configuration found for model: ${modelId}`);
    return null;
  }

  console.log(`✅ Found endpoint for ${modelId}: ${endpoint.endpoint}`);
  return endpoint;
}

/**
 * Build request body according to endpoint format
 */
function buildRequestBody(endpointConfig, userParameters, callbackUrl) {
  const body = {};

  // Check if this endpoint uses the standard /jobs/createTask format
  if (endpointConfig.endpoint.includes('/jobs/createTask')) {
    // Standard format: { model: "...", callBackUrl: "...", input: {...} }
    const modelName = extractModelName(endpointConfig, userParameters);

    body.model = modelName;
    body.callBackUrl = callbackUrl;
    body.input = buildInputParameters(endpointConfig, userParameters);

  } else {
    // Custom format: parameters go directly in body
    Object.assign(body, buildInputParameters(endpointConfig, userParameters));

    // Add callBackUrl if supported
    if (endpointConfig.parameters?.required?.callBackUrl ||
        endpointConfig.parameters?.optional?.callBackUrl) {
      body.callBackUrl = callbackUrl;
    }
  }

  return body;
}

/**
 * Extract the actual model name to send to KIE.AI
 */
function extractModelName(endpointConfig, userParameters) {
  // Check if user provided model name
  if (userParameters.model) {
    return userParameters.model;
  }

  // Check endpoint config for default model name
  if (endpointConfig.parameters?.required?.model?.default) {
    return endpointConfig.parameters.required.model.default;
  }

  if (endpointConfig.parameters?.required?.model?.value) {
    return endpointConfig.parameters.required.model.value;
  }

  if (endpointConfig.parameters?.optional?.model?.default) {
    return endpointConfig.parameters.optional.model.default;
  }

  // Fallback to first modelId
  return endpointConfig.modelIds?.[0] || 'unknown';
}

/**
 * Build input parameters with defaults
 */
function buildInputParameters(endpointConfig, userParameters) {
  const input = {};

  // Add user-provided parameters
  Object.keys(userParameters).forEach(key => {
    // Skip 'model' as it goes in top-level for /jobs/createTask
    if (key !== 'model' || !endpointConfig.endpoint.includes('/jobs/createTask')) {
      input[key] = userParameters[key];
    }
  });

  // Add defaults for required parameters if not provided
  if (endpointConfig.parameters?.required) {
    Object.entries(endpointConfig.parameters.required).forEach(([key, param]) => {
      if (!input[key] && param.default !== undefined && key !== 'model' && key !== 'callBackUrl') {
        input[key] = param.default;
        console.log(`Adding required default: ${key} = ${JSON.stringify(param.default)}`);
      }
    });
  }

  // Add defaults for optional parameters if not provided
  if (endpointConfig.parameters?.optional) {
    Object.entries(endpointConfig.parameters.optional).forEach(([key, param]) => {
      if (!input[key] && param.default !== undefined && key !== 'callBackUrl') {
        input[key] = param.default;
        console.log(`Adding optional default: ${key} = ${JSON.stringify(param.default)}`);
      }
    });
  }

  return input;
}

/**
 * Calculate credits cost for a request
 */
function calculateCreditsCost(endpointConfig, parameters) {
  if (!endpointConfig.pricing) {
    return 10; // Default cost
  }

  const pricing = endpointConfig.pricing;

  // If fixed price
  if (pricing.credits) {
    return pricing.credits;
  }

  // If variable price based on parameters (video duration, resolution, etc.)
  // TODO: Implement dynamic pricing calculation

  return 10;
}

/**
 * Main routing function
 */
async function routeRequest(modelId, userParameters, callbackUrl, apiKey) {
  console.log(`🔀 Routing request for model: ${modelId}`);

  // Find endpoint configuration
  const endpointConfig = findEndpointForModel(modelId);
  if (!endpointConfig) {
    throw new Error(`Model not supported: ${modelId}`);
  }

  // Build request body
  const body = buildRequestBody(endpointConfig, userParameters, callbackUrl);

  // Calculate credits cost
  const creditsCost = calculateCreditsCost(endpointConfig, userParameters);

  // Build full URL
  const fullUrl = endpointConfig.full_url || `https://api.kie.ai${endpointConfig.endpoint}`;

  console.log(`📤 Sending to: ${fullUrl}`);
  console.log(`💳 Credits cost: ${creditsCost}`);
  console.log(`📦 Body:`, JSON.stringify(body, null, 2));

  // Make request to KIE.AI
  const response = await fetch(fullUrl, {
    method: endpointConfig.method || 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify(body)
  });

  const result = await response.json();

  return {
    success: result.code === 200,
    result: result,
    creditsCost: creditsCost,
    endpointUsed: endpointConfig.endpoint
  };
}

module.exports = {
  routeRequest,
  findEndpointForModel,
  calculateCreditsCost,
  loadEndpointsMapping
};
